version: '3.1'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
    - MYSQL_USER=root
    - MYSQL_ROOT_PASSWORD=123456
    ports: 
    - "3306:3306"